# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='image_file',
            field=models.FileField(null=True, upload_to='sound_images/'),
        ),
    ]
